"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabase } from "@/lib/supabase";

type Order = { id:string; external_order_id:string|null; tracking_id:string|null; pidge_order_id:string|null; rider_id:string|null; customer_name:string|null; customer_phone:string|null; pickup_address:string|null; drop_address:string|null; status:string|null; updated_at:string|null };
type Rider = { id:string; name:string|null; phone:string|null; vehicle_number:string|null; status:string|null; last_lat:number|null; last_lng:number|null; last_seen_at:string|null };
type View = "overview"|"orders"|"riders"|"exceptions"|"clients"|"pidge"|"reports"|"settings";
const LIVE=["created","validated","pushed_to_pidge","assigned","picked_up","out_for_delivery"];
const label=(v:string|null)=>(v||"Unknown").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function Home(){
 const [orders,setOrders]=useState<Order[]>([]),[riders,setRiders]=useState<Rider[]>([]),[view,setView]=useState<View>("overview"),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[selected,setSelected]=useState<Order|null>(null),[live,setLive]=useState(false),[error,setError]=useState(""),[createOpen,setCreateOpen]=useState(false),[adminOpen,setAdminOpen]=useState(false),[fullscreen,setFullscreen]=useState(false),[loading,setLoading]=useState(false),[pushingPidge,setPushingPidge]=useState(false),[form,setForm]=useState({external_order_id:"",customer_name:"",customer_phone:"",pickup_address:"",drop_address:""});
 const load=async()=>{setLoading(true);setError("");try{const sb=getSupabase();const [a,b]=await Promise.all([sb.from("orders").select("*").order("updated_at",{ascending:false}).limit(500),sb.from("riders").select("*").limit(500)]);if(a.error)throw a.error;if(b.error)throw b.error;setOrders((a.data||[]) as Order[]);setRiders((b.data||[]) as Rider[])}catch(e){setError(e instanceof Error?e.message:"Unable to load data")}finally{setLoading(false)}};
 useEffect(()=>{let mounted=true;const sb=getSupabase();load();const ch=sb.channel("bmx-control-tower").on("postgres_changes",{event:"*",schema:"public",table:"orders"},p=>{if(!mounted)return;setOrders(c=>p.eventType==="INSERT"?[p.new as Order,...c]:p.eventType==="UPDATE"?c.map(o=>o.id===p.new.id?p.new as Order:o):c.filter(o=>o.id!==p.old.id))}).on("postgres_changes",{event:"*",schema:"public",table:"riders"},p=>{if(!mounted)return;setRiders(c=>p.eventType==="INSERT"?[p.new as Rider,...c]:p.eventType==="UPDATE"?c.map(r=>r.id===p.new.id?p.new as Rider:r):c.filter(r=>r.id!==p.old.id))}).on("postgres_changes",{event:"INSERT",schema:"public",table:"rider_locations"},p=>{const x=p.new as any;setRiders(c=>c.map(r=>r.id===x.rider_id?{...r,last_lat:x.latitude,last_lng:x.longitude,last_seen_at:x.recorded_at,status:"online"}:r))}).subscribe(s=>mounted&&setLive(s==="SUBSCRIBED"));return()=>{mounted=false;sb.removeChannel(ch)}},[]);
 const filtered=useMemo(()=>orders.filter(o=>{const f=filter==="all"||(filter==="live"?LIVE.includes(o.status||""):o.status===filter);return f&&[o.external_order_id,o.tracking_id,o.pidge_order_id,o.customer_name,o.customer_phone,o.drop_address].join(" ").toLowerCase().includes(search.toLowerCase())}),[orders,filter,search]);
 const stats={total:orders.length,live:orders.filter(o=>LIVE.includes(o.status||"")).length,assigned:orders.filter(o=>o.status==="assigned").length,delivery:orders.filter(o=>o.status==="out_for_delivery").length,delivered:orders.filter(o=>o.status==="delivered").length};
 const nav=(v:View)=>{setView(v);setSelected(null);setFilter(v==="exceptions"?"failed":v==="orders"?"live":"all")};
 const createOrder=async()=>{try{const sb=getSupabase();const tracking=`BMX-${Date.now().toString(36).toUpperCase()}`;const {data,error}=await sb.from("orders").insert({external_order_id:form.external_order_id||tracking,tracking_id:tracking,customer_name:form.customer_name,customer_phone:form.customer_phone,pickup_address:form.pickup_address,drop_address:form.drop_address,status:"created"}).select().single();if(error)throw error;setOrders(c=>[data as Order,...c]);setCreateOpen(false);setForm({external_order_id:"",customer_name:"",customer_phone:"",pickup_address:"",drop_address:""});setView("orders")}catch(e){setError(e instanceof Error?e.message:"Create order failed")}};
 const pushToPidge=async()=>{if(!selected||pushingPidge)return;setPushingPidge(true);setError("");try{const sb=getSupabase();const {data,error}=await sb.functions.invoke("pidge-push-order",{body:{order_id:selected.id}});if(error)throw error;if(data?.error)throw new Error(`${data.error}${data.details?` — ${JSON.stringify(data.details)}`:""}`);const refreshed=data?.order as Order|undefined;if(refreshed){setOrders(c=>c.map(o=>o.id===refreshed.id?refreshed:o));setSelected(refreshed)}else{await load();const {data:latest,error:latestError}=await sb.from("orders").select("*").eq("id",selected.id).single();if(!latestError&&latest){setSelected(latest as Order)}}}catch(e){setError(e instanceof Error?e.message:"Pidge push failed")}finally{setPushingPidge(false)}};
 const status=async(s:string)=>{if(!selected)return;try{const sb=getSupabase();const {data,error}=await sb.from("orders").update({status:s,updated_at:new Date().toISOString()}).eq("id",selected.id).select().single();if(error)throw error;setOrders(c=>c.map(o=>o.id===selected.id?data as Order:o));setSelected(data as Order);await sb.from("tracking_events").insert({order_id:selected.id,status:s,event_type:"status_update",description:`Status changed to ${label(s)}`})}catch(e){setError(e instanceof Error?e.message:"Status update failed")}};
 const toggleFullscreen=async()=>{try{if(!document.fullscreenElement){await document.documentElement.requestFullscreen();setFullscreen(true)}else{await document.exitFullscreen();setFullscreen(false)}}catch{setError("Fullscreen is not available in this browser")}};
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">BX</span><div><b>BM XPRESS</b><small>CONTROL TOWER</small></div></div><nav className="nav"><div className="nav-section">OPERATIONS</div><button className={`nav-item ${view==="overview"?"active":""}`} onClick={()=>nav("overview")}>⌁ <span>Live Overview</span></button><button className={`nav-item ${view==="orders"?"active":""}`} onClick={()=>nav("orders")}>◉ <span>Live Orders</span><em>{stats.live}</em></button><button className={`nav-item ${view==="riders"?"active":""}`} onClick={()=>nav("riders")}>⌖ <span>Rider Tracking</span></button><button className={`nav-item ${view==="exceptions"?"active":""}`} onClick={()=>nav("exceptions")}>◫ <span>Exceptions</span></button><div className="nav-section">MANAGEMENT</div><button className={`nav-item ${view==="clients"?"active":""}`} onClick={()=>nav("clients")}>▣ <span>Clients</span></button><button className={`nav-item ${view==="riders"?"active":""}`} onClick={()=>nav("riders")}>▤ <span>Riders</span></button><button className={`nav-item ${view==="pidge"?"active":""}`} onClick={()=>nav("pidge")}>⇄ <span>Pidge Integration</span></button><button className={`nav-item ${view==="reports"?"active":""}`} onClick={()=>nav("reports")}>▥ <span>Reports</span></button><div className="nav-section">SYSTEM</div><button className={`nav-item ${view==="settings"?"active":""}`} onClick={()=>nav("settings")}>⚙ <span>Settings</span></button></nav><div className="sidebar-foot"><span className="health-dot"/> {live?"All systems operational":"Connecting to realtime"}</div></aside>
 <main className="main-shell"><header className="topbar"><div><div className="eyebrow">SUPER ADMIN</div><h1>{view==="overview"?"Live Operations":label(view)}</h1><p>BM XPRESS delivery control tower.</p></div><div className="top-actions"><button className="connection" onClick={load}><span/>{live?"Realtime connected":"Reconnect"}</button><button className="icon-btn" onClick={load} title="Refresh">↻</button><button className="admin-avatar" onClick={()=>setAdminOpen(v=>!v)}>BA</button>{adminOpen&&<div className="admin-menu"><b>BM XPRESS Admin</b><button onClick={()=>nav("settings")}>Account settings</button><button onClick={()=>setAdminOpen(false)}>Close</button></div>}</div></header><section className="content">{error&&<div className="error-banner">{error}<button onClick={()=>setError("")}>×</button></div>}
 {view==="overview"&&<><div className="stats-grid"><div className="metric-card"><span className="metric-label">TOTAL ORDERS</span><strong>{stats.total}</strong><span className="metric-note">Today</span></div><div className="metric-card accent"><span className="metric-label">LIVE ORDERS</span><strong>{stats.live}</strong><span className="metric-note positive">● Updating live</span></div><div className="metric-card"><span className="metric-label">ASSIGNED</span><strong>{stats.assigned}</strong><span className="metric-note">Riders assigned</span></div><div className="metric-card"><span className="metric-label">OUT FOR DELIVERY</span><strong>{stats.delivery}</strong><span className="metric-note">On road</span></div><div className="metric-card"><span className="metric-label">DELIVERED</span><strong>{stats.delivered}</strong><span className="metric-note">Completed</span></div></div><div className="section-head"><div><h2>Live Network</h2><p>Real-time rider positions.</p></div><div className="network-status"><span className="health-dot"/> {riders.filter(r=>r.status==="online").length} riders online</div></div><div className="network-grid"><div className="map-card"><div className="map-header"><div><b>Rider location</b><span>Live GPS positions</span></div><button className="map-control" onClick={toggleFullscreen}>{fullscreen?"Exit fullscreen":"Full screen ↗"}</button></div><div className="map-surface"><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><div className="map-road r4"/>{riders.filter(r=>r.last_lat!==null&&r.last_lng!==null).map((r,i)=><button key={r.id} className="rider-pin" style={{left:`${12+(i*31)%76}%`,top:`${17+(i*47)%68}%`}} title={r.name||"Rider"} onClick={()=>setError(`${r.name||"Rider"} • ${r.phone||"No phone"} • ${r.vehicle_number||"Vehicle pending"}`)}>●</button>)}{!riders.some(r=>r.last_lat!==null&&r.last_lng!==null)&&<div className="map-empty"><b>Live map ready</b><span>Rider GPS locations appear when Pidge callbacks arrive.</span></div>}<div className="map-legend"><span>● Rider GPS</span><span>{riders.length} riders</span></div></div></div><div className="side-card"><div className="side-card-title"><div><b>Operations health</b><span>System status</span></div><span className="healthy">Healthy</span></div><div className="health-row"><span>Realtime stream</span><b>{live?"Connected":"Connecting"}</b></div><div className="health-row"><span>Riders</span><b>{riders.length}</b></div><div className="health-row"><span>Pidge gateway</span><b className="muted-text">Ready</b></div><div className="health-row"><span>AI ETA engine</span><b className="muted-text">Ready</b></div></div></div></>}
 {(view!=="overview"&&view!=="orders"&&view!=="riders"&&view!=="exceptions")&&<div className="orders-card"><div className="section-head"><div><h2>{label(view)}</h2><p>{view==="pidge"?"Pidge integration and API activity.":view==="clients"?"Client accounts and API connectivity.":view==="reports"?"Operational reporting workspace.":"Control Tower configuration."}</p></div></div><div className="empty-state"><b>{label(view)} module</b><span>Module navigation is active. Connect the corresponding Supabase/API workflow next.</span></div></div>}
 {(view==="orders"||view==="riders"||view==="exceptions"||view==="overview")&&<><div className="section-head orders-head"><div><h2>{view==="riders"?"Riders":"Live Orders"}</h2><p>{view==="riders"?"Current rider records and GPS status.":"Every status change appears automatically."}</p></div>{view!=="riders"&&<button className="primary-btn" onClick={()=>setCreateOpen(true)}>+ Create Order</button>}</div>{view==="riders"?<div className="orders-card"><div className="table-wrap"><table className="orders-table"><thead><tr><th>RIDER</th><th>PHONE</th><th>VEHICLE</th><th>STATUS</th><th>GPS</th><th>LAST SEEN</th></tr></thead><tbody>{riders.map(r=><tr key={r.id}><td><b>{r.name||"Unnamed rider"}</b></td><td>{r.phone||"—"}</td><td>{r.vehicle_number||"—"}</td><td><span className="status-pill">{label(r.status)}</span></td><td>{r.last_lat!==null&&r.last_lng!==null?`${r.last_lat}, ${r.last_lng}`:"No GPS"}</td><td>{r.last_seen_at?new Date(r.last_seen_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div></div>:<div className="orders-card"><div className="toolbar"><div className="search-box"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, tracking ID, customer..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All orders</option><option value="live">Live orders</option><option value="assigned">Assigned</option><option value="picked_up">Picked up</option><option value="out_for_delivery">Out for delivery</option><option value="delivered">Delivered</option><option value="failed">Failed</option></select></div><div className="table-wrap"><table className="orders-table"><thead><tr><th>ORDER</th><th>TRACKING ID</th><th>CUSTOMER</th><th>RIDER</th><th>STATUS</th><th>LAST UPDATE</th><th/></tr></thead><tbody>{filtered.map(o=>{const r=riders.find(x=>x.id===o.rider_id);return <tr key={o.id} onClick={()=>setSelected(o)}><td><b>{o.external_order_id||"—"}</b><small>{o.pidge_order_id||"Pidge pending"}</small></td><td>{o.tracking_id||"—"}</td><td><b>{o.customer_name||"Unknown"}</b><small>{o.customer_phone||"—"}</small></td><td>{r?.name||"Unassigned"}</td><td><span className={`status-pill ${o.status||""}`}>{label(o.status)}</span></td><td>{o.updated_at?new Date(o.updated_at).toLocaleString():"—"}</td><td className="arrow">›</td></tr>})}</tbody></table></div>{!filtered.length&&<div className="empty-state"><b>No orders found</b><span>Try another filter or create an order.</span></div>}</div>}</>}
 </section></main>
 {createOpen&&<div className="drawer-backdrop" onClick={()=>setCreateOpen(false)}><div className="order-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setCreateOpen(false)}>×</button><div className="eyebrow">NEW ORDER</div><h2>Create Order</h2>{Object.entries({external_order_id:"External order ID",customer_name:"Customer name",customer_phone:"Customer phone",pickup_address:"Pickup address",drop_address:"Delivery address"}).map(([k,l])=><input key={k} className="form-input" placeholder={l} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<button className="primary-btn" onClick={createOrder} disabled={loading}>{loading?"Creating...":"Create Order"}</button></div></div>}
 {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="order-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">ORDER DETAILS</div><h2>{selected.external_order_id||selected.tracking_id}</h2><span className={`status-pill ${selected.status||""}`}>{label(selected.status)}</span><div className="drawer-block"><span>Tracking ID</span><b>{selected.tracking_id||"—"}</b></div><div className="drawer-block"><span>Customer</span><b>{selected.customer_name||"—"}</b><small>{selected.customer_phone||""}</small></div><div className="drawer-block"><span>Pickup</span><b>{selected.pickup_address||"—"}</b></div><div className="drawer-block"><span>Delivery</span><b>{selected.drop_address||"—"}</b></div><div className="drawer-block"><span>Pidge order</span><b>{selected.pidge_order_id||"Pending"}</b></div><div className="drawer-actions"><button className="primary-btn" onClick={pushToPidge} disabled={pushingPidge||!!selected.pidge_order_id}>{pushingPidge?"Pushing to Pidge...":selected.pidge_order_id?"✓ Already in Pidge":"Push to Pidge"}</button>{["assigned","picked_up","out_for_delivery","delivered","failed"].map(s=><button key={s} onClick={()=>status(s)}>{label(s)}</button>)}</div></aside></div>}
 </div>;
}
